# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # START
    - name: Step 1
      run: echo Begin deployment...
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Ruby setup https://github.com/ruby/setup-ruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 
        bundler-cache: true 
    
    # Node setup https://github.com/actions/setup-node 
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12'
        
    # Update package managers   
    - name: Update pkg managers
      run: |
        gem update bundler
        sudo npm install -g npm@latest
        
    # Check versions    
    - name: Check version
      run: |
        bundle --version 
        npm -v
        ruby -v
        
    # Install Google Firebase tools
    - name: Install Firebase tools
      run: |
        sudo npm install firebase-functions@latest 
        sudo npm install firebase-admin@latest 
        sudo npm install -g firebase-tools
      
    # Kick off a build of Jekyll pages
    - name: Jekyll build
      run: bundle exec jekyll build --verbose
    
      # Deploy to firebase
    - name: Deploy to Firebase
      run: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
