# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Ruby setup https://github.com/ruby/setup-ruby
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 
        bundler-cache: true 
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    # Runs a single command using the runners shell
    - name: Step 1
      run: echo Begin deployment...
    
    # Install   
    - name: Step 2
      run: |
        gem update bundler
        npm install
    
    # Check versions    
    - name: Step 3
      run: |
        bundle --version 
        npm -v
        ruby -v
        
    # Install Google Firebase tools
    - name: Step 4
      run: sudo npm install -g firebase-tools
      
    # Kick off a build of Jekyll pages
    - name: Step 5
      run: bundle exec jekyll build --verbose
    
  #  - name: Download Artifact
   #   uses: actions/download-artifact@v2
    #  with:
     #   name: dist
      #  path: dist

    #- name: Deploy to Firebase
     # uses: w9jds/firebase-action@master
      #with:
       # args: deploy --only hosting
      #env:
       # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


      
      #"$FIREBASE_TOKEN"
    - name: Step 6
      run: firebase deploy --token $FIREBASE_TOKEN --non-interactive
     
